#!/bin/bash
# render all svg files in the current folder and return rendered files
# in a xml file called rendered-files

# this file should be run in context of where it's located
cd "$(dirname ${BASH_SOURCE[0]})" || exit 1

render_blender () {
  echoreport rendering "$1"...
  blender -b "$1" -a >/dev/null
}

for i in *.blend; do
  render_blender "$i"
done

list_rendered () {
  printf "["
  for i in *.png; do
    printf \"
    printf "%s" "$i" # SC2059. filenames could contain '%' which would be parsed
    printf \"
    printf ","
  done | sed s/,$// # remove trailing comma
  printf ']\n' # single quote so \n is parsed by printf not bash
}

list_rendered > rendered-files
