#!/bin/bash
# render all mmpz files in the current folder and return rendered files
# in a json file called to-move

# this file should be run in context of where it's located
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

cp ./osu-resources/osu.Game.Resources/Samples/Gameplay/*.wav ./
# Use Argon Pro samples
cp ./osu-resources/osu.Game.Resources/Samples/Gameplay/ArgonPro/*.wav ./

list_rendered () {
  printf "["
  for i in *.wav; do
    printf \"
    printf "%s" "$i" # SC2059. filenames could contain '%' which would be parsed
    printf \"
    printf ","
  done | sed s/,$// # remove trailing comma
  printf ']\n' # single quote so \n is parsed by printf not bash
}

list_rendered > to-move
