#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
source _common/convert.bash

render_blender_marker ranking-panel.blend --python-text "sync-score-text"

list_rendered () {
  printf "["
  for i in *.png; do
    printf \"
    printf "%s" "$i"
    printf \"
    printf ","
  done | sed s/,$// # remove trailing comma
  printf ']\n'
}

list_rendered > to-move
