#!/bin/bash
# render all svg files in the current folder and return rendered files
# in a xml file called rendered-files

# this file should be run in context of where it's located
cd "$(dirname ${BASH_SOURCE[0]})" || exit 1

read -r -d '' render_marker <<'PYTHON'
# by p2or on Blender StackExchange
# https://blender.stackexchange.com/questions/23121
import bpy
import os

# get the scene
scn = bpy.context.scene

# get the output path
output_path = scn.render.filepath

# iterate through markers and render
for k, m in scn.timeline_markers.items():
    frame = m.frame
    marker_name = m.name
    scn.frame_set(frame)
    scn.render.filepath = os.path.join(output_path, marker_name + ".jpg")
    bpy.ops.render.render( write_still=True )

bpy.context.scene.render.filepath = output_path
PYTHON

render_blender_marker () {
    echo "render_blender_marker: $1"
    blender -b "$1" --python <(echo "$render_marker") >/dev/null 2>/dev/null
}

for i in *.blend; do
  render_blender_marker "$i"
done

list_rendered () {
  printf "["
  for i in *.png; do
    printf \"
    printf "%s" "$i" # SC2059. filenames could contain '%' which would be parsed
    printf \"
    printf ","
  done | sed s/,$// # remove trailing comma
  printf ']\n' # single quote so \n is parsed by printf not bash
}

list_rendered > rendered-files
