#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

list_rendered () {
  printf "["
  for i in $1; do
    printf \"
    printf "%s" "$i" # SC2059. filenames could contain '%' which would be parsed
    printf \"
    printf ","
  done | sed s/,$// # remove trailing comma
  printf ']\n' # single quote so \n is parsed by printf not bash
}

list_rendered "$(find ./* -not -name 'to-move' -not -name "to-copy" -not -name 'render')" > to-copy
