#!/bin/bash

cd "$(dirname ${BASH_SOURCE[0]})" || exit 1

./render-marker
./render-blender
./render-svg

list_rendered () {
  printf "["
  for i in *.png; do
    printf \"
    printf "%s" "$i" # SC2059. filenames could contain '%' which would be parsed
    printf \"
    printf ","
  done | sed s/,$// # remove trailing comma
  printf ']\n' # single quote so \n is parsed by printf not bash
}

list_rendered > rendered-files
